name: audiobookly
description: An audiobook player for Plex built using Flutter.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

publish_to: none
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  plex_api:
    path: ./plex_api
  emby_api:
    path: ./emby_api
  flutter_hooks: ^0.17.0
  hooks_riverpod: ^0.14.0+4
  expandable: ^5.0.1
  cached_network_image: ^3.0.0
  audio_session: ^0.1.0
  audio_service: ^0.18.0-beta.0
  just_audio: ^0.9.5
  shared_preferences: ^2.0.5
  marquee: ^2.1.0
  path: ^1.8.0
  path_provider: ^2.0.1
  animations: ^2.0.0
  url_launcher: ^6.0.3
  rxdart: ^0.27.1
  # flutter_inappwebview:
  freezed_annotation: ^0.14.1
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  dart_vlc: ^0.1.6
  # audio_cast:
  cast:
  collection: ^1.15.0-nullsafety.4
  # objectbox: ^1.0.0
  floor:
  auto_size_text: ^3.0.0-nullsafety.0
  device_info_plus:
  get_it: ^7.1.4
  flutter_downloader:

dev_dependencies:
  build_runner: ^2.0.2
  freezed: ^0.14.1+3
  # objectbox_generator:
  floor_generator:
  flutter_lints: ^1.0.3
  flutter_launcher_icons: "^0.9.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/audiobookly_launcher_round.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Jump
      fonts:
        - asset: fonts/Jump.ttf
