name: audiobookly
description: An audiobook player for Plex built using Flutter.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0+10

environment:
  sdk: ">=3.0.0 <4.0.0"

publish_to: none
dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  plex_api:
    path: ./plex_api
  emby_api:
    path: ./emby_api
  audiobookshelf:
    path: ./audiobookshelf_api
  flutter_hooks: ^0.20.0
  hooks_riverpod: ^2.0.2
  expandable: ^5.0.1
  cached_network_image: ^3.0.0
  socket_io_client: ^3.0.0
  audio_session: ^0.1.6+1
  audio_service: ^0.18.4
  just_audio: any
  path: ^1.8.0
  path_provider: ^2.0.1
  animations: ^2.0.0
  url_launcher: ^6.0.3
  rxdart: ^0.27.1
  # flutter_inappwebview:
  freezed_annotation: ^2.0.3
  scrollable_positioned_list: ^0.3.2
  # audio_cast:
  # cast:
  auto_size_text: ^3.0.0-nullsafety.0
  device_info_plus: ^11.1.0
  get_it: ^8.0.1
  flutter_cache_manager:
  reorderable_grid_view: ^2.2.1
  isar: ^3.0.0
  isar_flutter_libs: ^3.0.0 # contains the binaries
  macos_ui:
  cupertino_icons:
  modal_bottom_sheet: ^3.0.0-pre
  clickup_fading_scroll:
    git:
      url: https://github.com/clickup/clickup_fading_scroll
  better_cupertino_slider: ^1.0.0
  background_downloader: ^8.0.5
  declarative_refresh_indicator: ^0.1.0
  adaptive_navigation: ^0.0.7
  scroll_to_index: ^3.0.1
  flutter_carplay:
    git:
      url: https://github.com/icapps/flutter_carplay.git
      ref: combine-all
  palette_generator: ^0.3.3+2
  flutter_riverpod: ^2.1.1
  flutter_adaptive_scaffold: ^0.3.1
  infinite_widgets: ^2.0.2
  flutter_adaptive_ui: ^0.8.0+1
  collection: ^1.17.1
  go_router: ^14.2.7
  riverpod_annotation: ^2.3.0
  flutter_to_airplay: ^2.0.5
  # just_audio_media_kit: ^1.0.0
  # just_audio_mpv: ^0.1.7

dev_dependencies:
  build_runner: ^2.0.2
  freezed: ^2.0.3+1
  isar_generator: ^3.0.0
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/new_ab_icon.png"
  adaptive_icon_background: "#673AB7"
  adaptive_icon_foreground: "assets/new_ab_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Jump
      fonts:
        - asset: fonts/Jump.ttf
